# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1F2120)
$foreground = rgb(DEE6DD)
$color0 = rgb(454746)
$color1 = rgb(141918)
$color2 = rgb(463528)
$color3 = rgb(305950)
$color4 = rgb(305950)
$color5 = rgb(855031)
$color6 = rgb(788A76)
$color7 = rgb(C7D3C6)
$color8 = rgb(8B948B)
$color9 = rgb(1A2220)
$color10 = rgb(5D4736)
$color11 = rgb(40776B)
$color12 = rgb(40776B)
$color13 = rgb(B16B42)
$color14 = rgb(A0B89E)
$color15 = rgb(C7D3C6)
