# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000001)
$foreground = rgb(F5E5CE)
$color0 = rgb(000001)
$color1 = rgb(445947)
$color2 = rgb(445947)
$color3 = rgb(6F532F)
$color4 = rgb(6F826A)
$color5 = rgb(72856C)
$color6 = rgb(A98956)
$color7 = rgb(E8D2B0)
$color8 = rgb(A2937B)
$color9 = rgb(5B775F)
$color10 = rgb(5B775F)
$color11 = rgb(946E3F)
$color12 = rgb(94AD8D)
$color13 = rgb(98B190)
$color14 = rgb(E1B672)
$color15 = rgb(E8D2B0)
