# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0D0000)
$foreground = rgb(FAEEC6)
$color0 = rgb(0D0000)
$color1 = rgb(3C1F0D)
$color2 = rgb(3F200E)
$color3 = rgb(6C3116)
$color4 = rgb(965921)
$color5 = rgb(965921)
$color6 = rgb(B49B45)
$color7 = rgb(EFDEA5)
$color8 = rgb(A79B74)
$color9 = rgb(502912)
$color10 = rgb(542A13)
$color11 = rgb(90411D)
$color12 = rgb(C8762C)
$color13 = rgb(C8762C)
$color14 = rgb(F0CE5C)
$color15 = rgb(EFDEA5)
